# Adversarial Attack Config
defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: null
save_path: 'outputs/oasst'

# env
env_name: guess_my_city
env_load_path: 'dataset/city_t5_oracle.pt'

# training hyperparameters
agent_type: "archer_offline"
capacity: 65143
batch_size: 16
iterations: 50 #total number of iterations
epochs: 5 #number of epochs for the critic each iteration
actor_epochs: 3 #number of epochs for the actor each iteration
warmup_iter: 0 #number of iterations without updating the policy
grad_accum_steps: 32
gamma: 0.99
critic_lr: 2e-5
lm_lr: 1e-5
inv_temp: 1.0
expetile_factor: 0.9
save_freq: 1
eval_freq: 1
eval_size: 5

# wandb logging
use_wandb: True
project_name: 'llm_rl_oasst'
run_name: 'archer-online'

