defaults:
  - default
  - _self_

# checkpoint
checkpoint_path: null
save_path: 'outputs/offline_archer_20q'

# env
env_name: twenty_questions
env_load_path: 'dataset/20q_t5_oracle.pt'

# training hyperparameters
agent_type: "archer_offline"
capacity: 100000
batch_size: 16
iterations: 50 #total number of iterations
epochs: 5 #number of epochs for the critic each iteration
actor_epochs: 3 #number of epochs for the actor each iteration
warmup_iter: 0 #number of iterations without updating the policy
grad_accum_steps: 8
gamma: 0.99
critic_lr: 1e-5
lm_lr: 1e-4
inv_temp: 1.0
expetile_factor: 0.9
save_freq: 1
eval_freq: 1
eval_size: 5

# wandb logging
use_wandb: True
project_name: 'llm_rl_20qsubset_offline'
run_name: 'archer-acc'